AWSTemplateFormatVersion: "2010-09-09"
Description: "Harjoitustemplaatti"
Resources:
  teroncfampari2:
    Type: "AWS::S3::Bucket"
  TeronQueue:
    Type: "AWS::SQS::Queue"
  TeronEC2:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: "ami-01f14919ba412de34"
      InstanceType: "t3.nano"